---
# MySQL installation and configuration

# Check current MySQL installation
- name: Check if MySQL is already installed
  command: mysql --version
  register: mysql_current_version
  failed_when: false
  changed_when: false

- name: Display current MySQL status
  debug:
    msg: "MySQL Status: {{ 'Already installed - ' + mysql_current_version.stdout if mysql_current_version.rc == 0 else 'Not installed, will install latest' }}"

# Add MySQL APT repository for latest version
- name: Download MySQL APT repository package
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
    dest: /tmp/mysql-apt-config.deb
    mode: '0644'
  when: mysql_current_version.rc != 0

- name: Install MySQL APT repository
  apt:
    deb: /tmp/mysql-apt-config.deb
    state: present
  when: mysql_current_version.rc != 0

- name: Update apt cache after adding MySQL repository
  apt:
    update_cache: yes
  when: mysql_current_version.rc != 0

# Install MySQL server with latest version
- name: Install MySQL server
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pymysql
    state: present

- name: Start and enable MySQL service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create MySQL configuration file for root
  template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress database user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ mysql_wordpress_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
